version: '3'

volumes:
  postgres_volume:
  redis-data:

services:
  chat_svc:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - local.env
    ports:
      - "50051:50051"
    networks:
      - cluster

  chat_db:
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - local.env
    ports:
      - "6431:5432"
    networks:
      - cluster
      - db

  chat_cache:
    image: redis:7.2.5-alpine
    ports:
      - "6371:6379"
    volumes:
      - redis-data:/data
    networks:
      - cluster

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    restart: on-failure
    env_file:
      - local.env
    environment:
      DB_HOST: chat_db
    networks:
      - db

networks:
  db:
  cluster:
    external: true
